---
# install_configure_EL7_HTCondor.yaml

- name: open HTCondor service port
  firewalld: zone=public port=9618/tcp  state=enabled immediate=yes permanent=yes
  when: (container is undefined) or (container == False)
  ignore_errors: yes

- name: open HTCondor ephemeral ports
  firewalld: zone=public port=40000-50000/tcp  state=enabled immediate=yes permanent=yes
  when: (container is undefined) or (container == False)
  ignore_errors: yes

- name: configure HTCondor repository
  get_url:
    url: http://research.cs.wisc.edu/htcondor/yum/repo.d/htcondor-stable-rhel7.repo
    dest: /etc/yum.repos.d/htcondor-stable-rhel7.repo
    mode: 0644

- name: install HTCondor repository GPG keys
  rpm_key:
    key: http://research.cs.wisc.edu/htcondor/yum/RPM-GPG-KEY-HTCondor
    state: present

- name: install HTCondor
  yum:
    name: ['condor-all']
    state: latest

- name: HTCondor local configuration
  copy:
    src: etc_condor_condor_config.local
    dest: /etc/condor/condor_config.local
    owner: root
    group: root
    mode: 0644
  notify:
  - reconfigure condor
  when: container is undefined

# If you ever use the IP address, change etc_condor_condor_config.local.container to a template.
# name: Get public IP address
# ipify_facts:
# when: 
# - container is defined
# - container == True

- name: HTCondor local container configuration
  copy:
    src: etc_condor_condor_config.local.container  
    dest: /etc/condor/condor_config.local
    owner: root
    group: root
    mode: 0644
  notify:
  - reconfigure condor
  when: container is defined  

- name: HTCondor configure 
  copy:
    src:  "etc_condor_config.d_{{ item }}"
    dest: "/etc/condor/config.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
  - default_request
  - defrag
  - ports
  - scaling
  - system_hold
  notify:
  - reconfigure condor

- name: install GSI tools
  yum:
    name: ['fetch-crl', 'globus-proxy-utils']
    state: latest
  when:
  - htcondor_cert is defined
  - htcondor_worker_cert is defined

- name: ensure fetch-crl-boot service is enabled and started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  ignore_errors: yes
  with_items:
  - fetch-crl-boot
  when:
  - htcondor_cert is defined
  - htcondor_worker_cert is defined

- name: ensure fetch-crl-cron service is enabled and started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
  - fetch-crl-cron
  when:
  - htcondor_cert is defined
  - htcondor_worker_cert is defined

- name: make sure fetch-crl is quiet about unsuccessful CRL validations
  copy:
    src:  etc_fetch-crl.d_noerrors.conf
    dest: /etc/fetch-crl.d/noerrors.conf
    owner: root
    group: root
    mode: 0644
  when:
  - htcondor_cert is defined
  - htcondor_worker_cert is defined

- name: HTCondor GSI configuration 
  template:
    src:  etc_condor_config.d_gsi.j2
    dest: /etc/condor/config.d/gsi
    owner: root
    group: root
    mode: 0644
  notify:
  - reconfigure condor
  when:
  - htcondor_cert is defined
  - htcondor_worker_cert is defined

- name: install the grid-mapfile if defined
  copy:
    src: etc_grid-security_grid-mapfile
    dest: /etc/grid-security/grid-mapfile
    owner: root
    group: root
    mode: 0644
  when:
  - grid_mapfile is defined
  - htcondor_cert is defined
  - htcondor_worker_cert is defined

- name: install host certificate file
  copy:
    src: "/etc/letsencrypt/live/{{ i_external_connection.0.ipv4fqdn }}/cert.pem"
    dest: /etc/grid-security/hostcert.pem
    remote_src: yes
    owner: root
    group: root
    mode: 0644
  when:
  - htcondor_cert is defined
  - htcondor_key is defined

- name: install host private key file
  copy:
    src: "/etc/letsencrypt/live/{{ i_external_connection.0.ipv4fqdn }}/privkey.pem"
    dest: /etc/grid-security/hostkey.pem
    remote_src: yes
    owner: root
    group: root
    mode: 0400
  when:
  - htcondor_cert is defined
  - htcondor_key is defined

- name: create condor certificate directories
  file:
    dest: /etc/grid-security/condor/worker
    state: directory
    owner: condor
    group: condor
    mode: 0755
  when:
  - htcondor_cert is defined
  - htcondor_worker_cert is defined

- name: ensure HTCondor is running
  service:
    name: condor
    enabled: yes
    state: started
  ignore_errors: yes

- name: install letsencrypt certificte chain
  shell: |
    git clone https://github.com/cilogon/letsencrypt-certificates.git
    cd letsencrypt-certificates/
    make check
    sudo make install
  args:
    executable: /bin/bash

- name: wait for condor
  wait_for:
    timeout: 5

- meta: flush_handlers
