---
# file: configure_ntpd.yaml - add local times server time.uvic.ca.

- name: install packages required by ntpd
  yum:
    name: ['ntp']
    state: latest

- name: configure ntpd
  copy: src=etc_ntp.conf dest=/etc/ntp.conf
  notify:
    - restart ntpd

- meta: flush_handlers

