---
# cloudscheduler (v2) server maim.yaml

- set_fact:
    public_mariadb: true

- include_vars: "{{ addenda }}"
- include_vars: "{{ inventory_instance }}-vars.yaml"
- include_vars: "{{ inventory_instance }}-secrets.yaml"

- import_tasks: configure_etc_hosts.yaml
- import_tasks: configure_sshd.yaml
  when: (container is undefined) or (container == False)
- import_tasks: create_installation_directories.yaml
- import_tasks: configure_other_required_repositories.yaml
- import_tasks: perform_yum_updates.yaml
- import_tasks: install_other_required_packages.yaml
- import_tasks: install_python_pip.yaml
- import_tasks: letsencrypt.yaml
  when: (local_web is undefined) or (local_web == False)
- import_tasks: create_localhost_cert.yaml
  when: 
  - local_web is defined
  - local_web == True
- import_tasks: install_python3.yaml
- import_tasks: configure_network.yaml
  when: (container is undefined) or (container == False)
- import_tasks: install_configure_ntpd.yaml
- import_tasks: set_root_user_defaults.yaml
- import_tasks: configure_volumes.yaml
  when: (container is undefined) or (container == False)
- import_tasks: configure_users.yaml
  when: (container is undefined) or (container == False)
- import_tasks: configure_sudoers.yaml
  when: (container is undefined) or (container == False)
- import_tasks: install_configure_MariaDB.yaml
- import_tasks: create_mysqldb_csv2.yaml
- import_tasks: install_configure_phpmyadmin.yaml
- import_tasks: install_EGI_trust_anchors.yaml
- import_tasks: install_configure_EL7_HTCondor.yaml
- import_tasks: install_configure_csv2.yaml
- import_tasks: install_configure_filebeat.yaml
- import_tasks: install_influxdb.yaml
