###
### This file should be encrypted with ansible-vault.
###

# Password used by csv2 to access the database.
mariadb_cloudscheduler: DFdWkLRK4Wk2HDhh

# Database root password.
mariadb_root: VEcqvYozrIUzL6jf

# If you want to change the database root password, set the current password
# here, the new password in "mariadb_root", and then run the ansible playbook.
mariadb_root_obsolete: d2NwxMB6zsbvVNr9

# Login password for phpMyadmin.
phpMyAdmin_secret: O388YO4m2GWnjAvd

# A fresh install create the "csv2_default" super user; this is the password.
csv2_default_password: something_you_can_remember

